version: '4'

services:

  mysql:
    image: bitnami/mysql:8.0
    container_name: mysql
    environment:
      MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: paimon
    volumes:
      - ../../../scripts/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    networks:
      - paimon

  minio:
    image: bitnami/minio:2025.4.8
    container_name: minio
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
      - MINIO_DEFAULT_BUCKETS=paimon:public
      - MINIO_PROMETHEUS_AUTH_TYPE=public # 低版本不起效，升级到最新版本
    ports:
      - 9000:9000
      - 9001:9001
    networks:
      - paimon

  jobmanager:
    image: flink:1.18.0-scala_2.12-java8
    container_name: jobmanager
    command: jobmanager
    environment:
      JOB_MANAGER_RPC_ADDRESS: jobmanager
      FLINK_PROPERTIES: |
        jobmanager.rpc.address: jobmanager
        s3.endpoint: http://minio:9000
        s3.access-key: admin
        s3.secret-key: password
        s3.path.style.access: true
    ports:
      - 8081:8081
    volumes:
      - /Users/wangqi/Documents/software/paimon/paimon-flink-1.18-0.8.1.jar:/opt/flink/lib/paimon-flink-1.18-0.8.1.jar
      - /Users/wangqi/Documents/software/paimon/paimon-flink-action-0.8.1.jar:/opt/flink/lib/paimon-flink-action-0.8.1.jar
      - /Users/wangqi/Documents/software/paimon/paimon-s3-0.8.1.jar:/opt/flink/lib/paimon-s3-0.8.1.jar
      - /Users/wangqi/Documents/software/paimon/flink-shaded-hadoop-2-uber-2.8.3-9.0.jar:/opt/flink/lib/flink-shaded-hadoop-2-uber-2.8.3-9.0.jar
    networks:
      - paimon

  taskmanager:
    image: flink:1.18.0-scala_2.12-java8
    container_name: taskmanager
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 1
    environment:
      JOB_MANAGER_RPC_ADDRESS: jobmanager
      TASK_MANAGER_NUMBER_OF_TASK_SLOTS: 8
      FLINK_PROPERTIES: |
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 8
        s3.endpoint: http://minio:9000
        s3.access-key: admin
        s3.secret-key: password
        s3.path.style.access: true
    volumes:
      - /Users/wangqi/Documents/software/paimon/paimon-flink-1.18-0.8.1.jar:/opt/flink/lib/paimon-flink-1.18-0.8.1.jar
      - /Users/wangqi/Documents/software/paimon/paimon-flink-action-0.8.1.jar:/opt/flink/lib/paimon-flink-action-0.8.1.jar
      - /Users/wangqi/Documents/software/paimon/paimon-s3-0.8.1.jar:/opt/flink/lib/paimon-s3-0.8.1.jar
      - /Users/wangqi/Documents/software/paimon/flink-shaded-hadoop-2-uber-2.8.3-9.0.jar:/opt/flink/lib/flink-shaded-hadoop-2-uber-2.8.3-9.0.jar
    networks:
      - paimon

  sql-gateway:
    image: flink:1.18.0-scala_2.12-java8
    container_name: sql-gateway
    depends_on:
      - jobmanager
      - taskmanager
    environment:
      JOB_MANAGER_RPC_ADDRESS: jobmanager
      FLINK_PROPERTIES: |
        jobmanager.rpc.address: jobmanager
        execution.target: remote
        rest.address: jobmanager
        rest.port: 8081
        s3.endpoint: http://minio:9000
        s3.access-key: admin
        s3.secret-key: password
        s3.path.style.access: true
    command: >
      /bin/sh -c "
      ./bin/sql-gateway.sh start-foreground -Dsql-gateway.endpoint.rest.address=0.0.0.0 -Drest.address=jobmanager
      "
    scale: 1
    ports:
      - 8083:8083
    volumes:
      - /Users/wangqi/Documents/software/paimon/paimon-flink-1.18-0.8.1.jar:/opt/flink/lib/paimon-flink-1.18-0.8.1.jar
      - /Users/wangqi/Documents/software/paimon/paimon-flink-action-0.8.1.jar:/opt/flink/lib/paimon-flink-action-0.8.1.jar
      - /Users/wangqi/Documents/software/paimon/paimon-s3-0.8.1.jar:/opt/flink/lib/paimon-s3-0.8.1.jar
      - /Users/wangqi/Documents/software/paimon/flink-shaded-hadoop-2-uber-2.8.3-9.0.jar:/opt/flink/lib/flink-shaded-hadoop-2-uber-2.8.3-9.0.jar
    networks:
      - paimon


# 默认用户名/密码是：admin/admin

networks:
  paimon:
    driver: bridge
